DNA = "ATTCGTTAGCTTATCTGGTTTGATGGCAACCCCGCTGTGAACTGCCGGAAGGATAGGGGGTAGTGGGTATTTAAAACATAGGCTAAACTCTGCGCCTGGACGCTTTTTTACCCAGTTTCGCGCGACGTTGGCTCGAAGGTATACAGTCCCCGCAAGTGAGGTAGGGAACACGACTATTTTCGCCTATCACTGAACGCGAGAAAACTCAAACATGGGCCCCCACTAACACTAGACCGGACATTCCGACACCCCTATTTTTTGAGAAGTGCCAACTCCTCTCATAGGCATTGTCTGCCGATGGGCCTAAAGTCTCTCGATCACTAAGATACTGATGAAACTACCACTTGGTGTGTATCATCCCCGTTCGGGGGAATGAATATGTTGGGCTTACCGATATAAAAATACCTCTTACAGTAGAAAAACTTAAATAGTTCTATCTATGGGACAGGGATCAGTGTACTGTCGAACGTATATATACATAGTGGAGCTCCCTCGTATCGCTTCTCTTCCCTACAAGCAATATGCTAAGAAGTTATGGTTACGCTGTGTGTAACGACGGGTCCTGGGCGATCTTGGTTGCCTCATGATCATGACTTTTTTAGTTTGCTGACTGAATGTGCCCGAGCGAAGGCAGTTGACCAGACTTGTGGATCAGACCCGCTACCGGCTGTCCCTGAGCTGGTGAGAGGTTCCGTGAAAGAAAACCGGGCTAACAGAATTGATAGCTGGGAGAGCCATGGAAGGATTTATACAGTTCGAGATCATCCTATCATTCTCTGCACAAGTGATCTCACATAACACCTAATTCCGACAAAATTTGGTCGTATGCCACTATGTTGGCAAAAGACTTGGCACTAACAAGACATGATACTGATTTCACTAACTATACCTAAGTCTATTTATGTTACCTTCTGAACTTTCGTCTCTACCCTAGAGTACGACTTTAAGTCAAGGACGATACTGTGTGGACGCAGGGATCCAGCGCAAGGCAATAGTGC"[::-1]
compliment_strand = ''
for char in DNA:
    if char == 'A':
        compliment_strand += 'T'
    elif char == 'T':
        compliment_strand += 'A'
    elif char == 'G':
        compliment_strand += 'C'
    elif char == 'C':
        compliment_strand += 'G'
print(compliment_strand)
